version: "3.5"
services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command:
      [
        "./wait-for-it.sh",
        "${DB_HOST}:${DB_PORT}",
        "-t",
        "120",
        "--",
        "./start-channels-worker.sh"
      ]
  redis:
    image: redis:latest

  db:
    image: postgres:10.1-alpine

  integration-tests:
    image: python:3.8-slim
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      sh -c "pip install tox && tox"

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "${DJANGO_BIND_PORT}:${DJANGO_BIND_PORT}"
    depends_on:
      - db
      - redis
      - worker
    command:
      [
        "./wait-for-it.sh",
        "${DB_HOST}:${DB_PORT}",
        "-t",
        "120",
        "--",
        "./start-development-server.sh",
      ]
